Cleanup of precommit (#167)
* WIP: Cleanup of precommit

* Update zpretty checks

* Fix reference to tox

* Apply suggestions from code review

Co-authored-by: Steve Piercy <web@stevepiercy.com>
Co-authored-by: David Glick <david@glicksoftware.com>

* Use package name for locales

* Add make target to clean the frontend folder

* Bump Python project version to 3.12

* README fix

* Update vscode settings

* Set ruff.target-version

* Re-use the plone version provided by the user

* Enable cache for uv installation

* Refactor Makefile

* Update Makefile for backend in a project

* Fix update-example-content target

* Fix BASE_TAG calculation on GHA

* Add repository.toml to project

* Update repository.toml

* Update repository.toml

* Project fixes

* Reuse variables

* add __python_version_identifier to the backend_addon

* Update README and add information about the format / lint available on a project

* Apply suggestions from code review

Co-authored-by: Steve Piercy <web@stevepiercy.com>

* Add check for cookieplone version

* Apply suggestions from code review

Co-authored-by: Steve Piercy <web@stevepiercy.com>

* Update cookieplone to 0.9.1

* Update volto examples to 18.10.0

* Use plone.autoinclude (Fixes #175)

* Fix hatch build options

* fix 'duplicate key  in table '

* Use cookieplone 0.9.3

* Add uv to requirements.txt

* Use tomli (to support Python 3.10)

* Fix backend tests

* Force ruff to use only alphabetical order for imports

* Pin cookiecutter-zope-instance to version 2.1.1

* Pin cookiecutter-zope-instance to version 2.1.1

* Improve error message for min cookieplone version

---------

Co-authored-by: Steve Piercy <web@stevepiercy.com>
Co-authored-by: David Glick <david@glicksoftware.com>

diff --git a/project/{{ cookiecutter.__folder_name }}/.github/workflows/backend.yml b/project/{{ cookiecutter.__folder_name }}/.github/workflows/backend.yml
--- a/project/{{ cookiecutter.__folder_name }}/.github/workflows/backend.yml
+++ b/project/{{ cookiecutter.__folder_name }}/.github/workflows/backend.yml
@@ -1,124 +1,150 @@
 name: Backend CI
 
 on:
-  push:
-    paths:
-      - "backend/**"
-      - ".github/workflows/backend.yml"
-  workflow_dispatch:
+  workflow_call:
+    inputs:
+      base-tag:
+        required: true
+        type: string
+      image-name-prefix:
+        required: true
+        type: string
+      image-name-suffix:
+        required: true
+        type: string
+      python-version:
+        required: true
+        type: string
+      plone-version:
+        required: true
+        type: string
 
-env:
-  IMAGE_NAME_PREFIX: {{ cookiecutter.__container_image_prefix }}
-  IMAGE_NAME_SUFFIX: backend
-  PYTHON_VERSION: "3.11"
+defaults:
+  run:
+    working-directory: backend
 
 jobs:
 
-  meta:
+  lint:
     runs-on: ubuntu-latest
-    outputs:
-      PLONE_VERSION: {{ "${{ steps.vars.outputs.PLONE_VERSION }}" }}
     steps:
-      - name: Checkout
-        uses: actions/checkout@{{ cookiecutter.__gha_version_checkout }}
 
-      - name: Set Env Vars
-        id: vars
-        run: |
-          echo "PLONE_VERSION=$(cat backend/version.txt)" >> $GITHUB_OUTPUT
+        - name: Checkout
+          uses: actions/checkout@{{ cookiecutter.__gha_version_checkout }}
 
-  black:
+        - name: Install the latest version of uv
+          uses: astral-sh/setup-uv@{{ cookiecutter.__gha_version_setup_uv }}
+          with:
+            python-version: {{ "${{ inputs.python-version }}" }}
+            enable-cache: true
+
+        - name: Check formatting
+          if: {{ "${{ success() || failure() }}" }}
+          id: ruff-format
+          run: uvx ruff@latest format --diff
+
+        - name: Check lint
+          if: {{ "${{ success() || failure() }}" }}
+          id: ruff-lint
+          run: uvx ruff@latest check --diff
+
+        - name: Check XML / ZCML
+          if: {{ "${{ success() || failure() }}" }}
+          id: zpretty
+          run: uvx zpretty@latest --check src
+
+        - name: Check Package Metadata
+          if: {{ "${{ success() || failure() }}" }}
+          id: pyroma
+          run: uvx pyroma@latest -d .
+
+        - name: Check Python Versions
+          if: {{ "${{ success() || failure() }}" }}
+          id: py-versions
+          run: uvx check-python-versions@latest .
+
+        - name: Report
+          if: {{ "${{ success() || failure() }}" }}
+          run: |
+            echo '# Code Analysis' >> $GITHUB_STEP_SUMMARY
+            echo '| Test | Status |' >> $GITHUB_STEP_SUMMARY
+            echo '| --- | --- |' >> $GITHUB_STEP_SUMMARY
+            echo '| Format | {{ "${{ steps.ruff-format.conclusion == 'failure' && '❌' || ' ✅' }}" }} |' >> $GITHUB_STEP_SUMMARY
+            echo '| Lint | {{ "${{ steps.ruff-lint.conclusion == 'failure' && '❌' || ' ✅' }}" }} |' >> $GITHUB_STEP_SUMMARY
+            echo '| XML / ZCML | {{ "${{ steps.zpretty.conclusion == 'failure' && '❌' || ' ✅' }}" }} |' >> $GITHUB_STEP_SUMMARY
+            echo '| Package Metadata | {{ "${{ steps.pyroma.conclusion == 'failure' && '❌' || ' ✅' }}" }} |' >> $GITHUB_STEP_SUMMARY
+            echo '| Python Versions | {{ "${{ steps.py-versions.conclusion == 'failure' && '❌' || ' ✅' }}" }} |' >> $GITHUB_STEP_SUMMARY
+
+  test:
+    runs-on: ubuntu-latest
+    env:
+      PYTHON_VERSION: {{ "${{ inputs.python-version }}" }}
+      PLONE_VERSION: {{ "${{ inputs.plone-version }}" }}
+    steps:
+
+        - name: Checkout
+          uses: actions/checkout@{{ cookiecutter.__gha_version_checkout }}
+
+        - name: Install the latest version of uv
+          uses: astral-sh/setup-uv@{{ cookiecutter.__gha_version_setup_uv }}
+          with:
+            python-version: {{ "${{ inputs.python-version }}" }}
+            enable-cache: false
+
+        - name: Restore uv cache
+          uses: actions/cache@{{ cookiecutter.__gha_version_cache }}
+          with:
+            path: {{ "${{ env.UV_CACHE_DIR }}" }}
+            key: uv-{{ "${{ runner.os }}-${{ inputs.python-version }}-${{ inputs.plone-version }}-${{ hashFiles('pyproject.toml') }}" }}
+            restore-keys: |
+              uv-{{ "${{ runner.os }}-${{ inputs.python-version }}-${{ inputs.plone-version }}-${{ hashFiles('pyproject.toml') }}" }}
+              uv-{{ "${{ runner.os }}-${{ inputs.python-version }}-${{ inputs.plone-version }}" }}
+
+        - name: Install Plone and package
+          run: make install
+
+        - name: Run tests
+          run: make test
+
+  coverage:
     runs-on: ubuntu-latest
     needs:
-      - meta
+      - test
     steps:
-      - name: Checkout codebase
-        uses: actions/checkout@{{ cookiecutter.__gha_version_checkout }}
+        - name: Checkout
+          uses: actions/checkout@{{ cookiecutter.__gha_version_checkout }}
 
-      - name: Run check
-        uses: plone/code-analysis-action@{{ cookiecutter.__gha_version_code_analysis }}
-        with:
-          base_dir: 'backend'
-          check: 'black'
+        - name: Install the latest version of uv
+          uses: astral-sh/setup-uv@{{ cookiecutter.__gha_version_setup_uv }}
+          with:
+            python-version: {{ "${{ inputs.python-version }}" }}
+            enable-cache: false
 
-  flake8:
-    runs-on: ubuntu-latest
-    needs:
-      - meta
-    steps:
-      - name: Checkout codebase
-        uses: actions/checkout@{{ cookiecutter.__gha_version_checkout }}
+        - name: Restore uv cache
+          uses: actions/cache@{{ cookiecutter.__gha_version_cache }}
+          with:
+            path: /tmp/.uv-cache
+            key: uv-{{ "${{ runner.os }}-${{ inputs.python-version }}-${{ inputs.plone-version }}-${{ hashFiles('pyproject.toml') }}" }}
+            restore-keys: |
+              uv-{{ "${{ runner.os }}-${{ inputs.python-version }}-${{ inputs.plone-version }}-${{ hashFiles('pyproject.toml') }}" }}
+              uv-{{ "${{ runner.os }}-${{ inputs.python-version }}-${{ inputs.plone-version }}" }}
 
-      - name: Run check
-        uses: plone/code-analysis-action@{{ cookiecutter.__gha_version_code_analysis }}
-        with:
-          base_dir: 'backend'
-          check: 'flake8'
+        - name: Install Plone and package
+          run: make install
 
-  isort:
-    runs-on: ubuntu-latest
-    needs:
-      - meta
-    steps:
-      - name: Checkout codebase
-        uses: actions/checkout@{{ cookiecutter.__gha_version_checkout }}
+        - name: Run tests
+          run: make test-coverage
 
-      - name: Run check
-        uses: plone/code-analysis-action@{{ cookiecutter.__gha_version_code_analysis }}
-        with:
-          base_dir: 'backend'
-          check: 'isort'
-
-  zpretty:
-    runs-on: ubuntu-latest
-    needs:
-      - meta
-    steps:
-      - name: Checkout codebase
-        uses: actions/checkout@{{ cookiecutter.__gha_version_checkout }}
-
-      - name: Run check
-        uses: plone/code-analysis-action@{{ cookiecutter.__gha_version_code_analysis }}
-        with:
-          base_dir: 'backend'
-          check: 'zpretty'
-
-  tests:
-    runs-on: ubuntu-latest
-    needs:
-      - meta
-    defaults:
-      run:
-        working-directory: ./backend
-
-    steps:
-      - uses: actions/checkout@{{ cookiecutter.__gha_version_checkout }}
-
-      - name: Setup Plone {{"${{ needs.meta.outputs.PLONE_VERSION }}"}} with Python {{"${{ env.PYTHON_VERSION }}"}}
-        uses: plone/setup-plone@v2.0.0
-        with:
-          python-version: ${{"{{ env.PYTHON_VERSION }}"}}
-          plone-version: ${{"{{ needs.meta.outputs.PLONE_VERSION }}"}}
-
-      - name: Install package
-        run: |
-          pip install mxdev
-          mxdev -c mx.ini
-          pip install -r requirements-mxdev.txt
-
-      - name: Run tests
-        run: |
-          pytest --disable-warnings tests
+        - name: Report Coverage
+          run: |
+            echo "# Coverage Report" >> $GITHUB_STEP_SUMMARY
+            echo "$(uv run coverage report --format markdown)" >> $GITHUB_STEP_SUMMARY
 
   release:
     runs-on: ubuntu-latest
     needs:
-      - meta
-      - black
-      - flake8
-      - isort
-      - zpretty
-      - tests
+      - lint
+      - coverage
     permissions:
       contents: read
       packages: write
@@ -133,9 +159,9 @@ jobs:
         uses: docker/metadata-action@{{ cookiecutter.__gha_version_docker_metadata }}
         with:
           images: |
-            {{ "${{ env.IMAGE_NAME_PREFIX }}-${{ env.IMAGE_NAME_SUFFIX }}" }}
+            {{ "${{ inputs.image-name-prefix }}-${{ inputs.image-name-suffix }}" }}
           labels: |
-            org.label-schema.docker.cmd=docker run -d -p 8080:8080 {{ "${{ env.IMAGE_NAME_PREFIX }}-${{ env.IMAGE_NAME_SUFFIX }}" }}:latest
+            org.label-schema.docker.cmd=docker run -d -p 8080:8080 {{ "${{ inputs.image-name-prefix }}-${{ inputs.image-name-suffix }}:${{ inputs.base-tag }}" }}
           flavor:
             latest=false
           tags: |
@@ -153,23 +179,23 @@ jobs:
         uses: docker/login-action@{{ cookiecutter.__gha_version_docker_login }}
         with:
           {%- if cookiecutter.container_registry == 'docker_hub' %}
-          username: {{"${{ secrets.DOCKERHUB_USERNAME }}"}}
-          password: {{"${{ secrets.DOCKERHUB_TOKEN }}"}}
+          username: {{ "${{ secrets.DOCKERHUB_USERNAME }}" }}
+          password: {{ "${{ secrets.DOCKERHUB_TOKEN }}" }}
           {%- endif %}
           {%- if cookiecutter.container_registry == 'github' %}
           registry: ghcr.io
-          username: {{"${{ github.actor }}"}}
-          password: {{"${{ secrets.GITHUB_TOKEN }}"}}
+          username: {{ "${{ github.actor }}" }}
+          password: {{ "${{ secrets.GITHUB_TOKEN }}" }}
           {%- endif %}
 
       - name: Build and push
         uses: docker/build-push-action@{{ cookiecutter.__gha_version_docker_build_push }}
         with:
           platforms: linux/amd64
-          context: backend
+          context: backend/
           file: backend/Dockerfile
-          push: {{"${{ github.event_name != 'pull_request' }}"}}
-          tags: {{"${{ steps.meta.outputs.tags }}"}}
-          labels: {{"${{ steps.meta.outputs.labels }}"}}
+          push: {{ "${{ github.event_name != 'pull_request' }}" }}
+          tags: {{ "${{ steps.meta.outputs.tags }}" }}
+          labels: {{ "${{ steps.meta.outputs.labels }}" }}
           build-args: |
-            PLONE_VERSION={{"${{ needs.meta.outputs.PLONE_VERSION }}"}}
+            PLONE_VERSION={{ "${{ inputs.plone-version }}" }}
